# Generated by Django 3.1.2 on 2020-10-21 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='pub_cate',
            new_name='pub_date',
        ),
    ]
